- hosts: all
  vars_files:
          - "{{ansible_facts['distribution']}}_{{ansible_facts['distribution_major_version']}}.yml"
  tasks:
        - package:
                name: "{{p}}"
                state: present
        - copy: 
                dest: "/var/www/html"
                src: nikhil.png
        -  service:
                name: "{{s}}"
                state: started
        -  service:
                name: firewalld
                state: stopped
                
